//! Count distinct terms in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100

use std::collections::HashSet;

use arbitrary_precision::Integer;

pub fn solve() -> usize {
    let mut set = HashSet::new();
    for a in (2..=100).map(Integer::from) {
        for b in 2_usize..=100 {
            set.insert(a.clone().pow(b));
        }
    }
    set.len()
}
